#!/usr/bin/env bash
# agents_md.sh — Splice a profile's content into AGENTS.md using
# HTML-comment markers, so re-installs and uninstalls leave the rest of
# the file untouched.
#
# Marker shape:
#   <!-- agent-profile:<profile>:begin -->
#   <body>
#   <!-- agent-profile:<profile>:end -->
#
# Re-install rewrites the block in place. Uninstall removes the block
# (and any trailing single blank line so we don't leave gaps).

set -euo pipefail

# Build the splice body from the resolved manifest's agents_md_blocks
# array plus optional inline degradations passed in via extra args
# (e.g. an `agents:` entry with fallback: inline that the renderer
# wants folded into AGENTS.md instead of getting its own file).
#
# Args: <merged_json> [title path]...
#       extra sections are passed as alternating title/path argument
#       pairs so titles may freely contain any character (':' included).
ap_build_agents_md_body() {
    local merged_json="$1"; shift
    local profile_name
    profile_name=$(jq -r '.name' <<<"$merged_json")

    {
        # shellcheck disable=SC2016  # literal backticks, not command substitution
        printf '<!-- Generated by `dots profile install %s`. Do not edit by hand. -->\n\n' "$profile_name"

        # Each block is a {name, content} pair from a profile in the
        # include chain. Header makes provenance obvious when a profile
        # composes several others.
        local count
        count=$(jq -r '.agents_md_blocks | length' <<<"$merged_json")
        local i=0
        while (( i < count )); do
            local block_name block_content
            block_name=$(jq -r ".agents_md_blocks[$i].name" <<<"$merged_json")
            block_content=$(jq -r ".agents_md_blocks[$i].content" <<<"$merged_json")
            if (( count > 1 )); then
                printf '## From profile: %s\n\n' "$block_name"
            fi
            printf '%s\n' "$block_content"
            printf '\n'
            i=$((i + 1))
        done

        # Append any extra inline sections (renderer-supplied
        # degradations). Args come in (title, path) pairs.
        while (($# >= 2)); do
            local title="$1" body_path="$2"
            shift 2
            [[ -f "$body_path" ]] || continue
            printf '## %s\n\n' "$title"
            cat "$body_path"
            printf '\n'
        done
    }
}

# Idempotent splice: replaces an existing block, or appends a new one.
ap_splice_agents_md() {
    local target_file="$1" profile="$2" body="$3"
    local begin="<!-- agent-profile:${profile}:begin -->"
    local end="<!-- agent-profile:${profile}:end -->"

    mkdir -p "$(dirname "$target_file")"
    [[ -f "$target_file" ]] || : > "$target_file"

    local tmp; tmp=$(mktemp)
    if grep -qF "$begin" "$target_file"; then
        # In-place rewrite of the existing block.
        awk -v begin="$begin" -v end="$end" -v body="$body" '
            $0 == begin { print; print body; print end; skip=1; next }
            $0 == end   { skip=0; next }
            !skip { print }
        ' "$target_file" > "$tmp"
    else
        # Append. Ensure a blank line separator if file already had
        # content.
        cp "$target_file" "$tmp"
        if [[ -s "$tmp" ]] && [[ "$(tail -c1 "$tmp" | od -An -c | tr -d ' ')" != '\n' ]]; then
            printf '\n' >> "$tmp"
        fi
        [[ -s "$tmp" ]] && printf '\n' >> "$tmp"
        {
            printf '%s\n' "$begin"
            printf '%s\n' "$body"
            printf '%s\n' "$end"
        } >> "$tmp"
    fi
    mv "$tmp" "$target_file"
}

# Strip the named profile's marker block. No-op if the block isn't
# present.
ap_strip_agents_md() {
    local target_file="$1" profile="$2"
    local begin="<!-- agent-profile:${profile}:begin -->"
    local end="<!-- agent-profile:${profile}:end -->"

    [[ -f "$target_file" ]] || return 0
    grep -qF "$begin" "$target_file" || return 0

    local tmp; tmp=$(mktemp)
    awk -v begin="$begin" -v end="$end" '
        $0 == begin { skip=1; next }
        skip && $0 == end { skip=0; next }
        skip { next }
        { print }
    ' "$target_file" > "$tmp"

    # Collapse a run of trailing blank lines down to zero, then add a
    # single terminating newline, so successive uninstalls do not eat
    # the file's normal trailing newline.
    awk 'NR==1{prev=$0; next}
         {print prev; prev=$0}
         END {if (prev != "") print prev}' "$tmp" > "$tmp.2"
    mv "$tmp.2" "$target_file"
    rm -f "$tmp"
}
