#!/usr/bin/env bash
# Shared sync helpers sourced by .sync.
# Logging, skip-list dispatch, per-entry sync, and bootstrap installers.
#
# Variables provided by the sourcing script: dir, olddir
# shellcheck disable=SC2154

# Colors
GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m' # No Color

log_info() {
    echo -e "${BLUE}[INFO]${NC} $1"
}

log_success() {
    echo -e "${GREEN}[SUCCESS]${NC} $1"
}

log_warning() {
    echo -e "${YELLOW}[WARNING]${NC} $1"
}

log_error() {
    echo -e "${RED}[ERROR]${NC} $1"
}

bootstrap_chezmoi_linux() {
    [[ "$(uname -s)" == "Linux" ]] || return 0
    command -v chezmoi &>/dev/null && return 0

    local bin_dir="$HOME/.local/bin"
    mkdir -p "$bin_dir"
    echo "  Installing chezmoi → $bin_dir (no system package available)"
    if ! curl -fsSL https://get.chezmoi.io | sh -s -- -b "$bin_dir"; then
        echo "  ERROR: chezmoi install script failed" >&2
        return 1
    fi
    hash -r 2>/dev/null || true
}

migrate_legacy_symlink() {
    local target="$1" dotfiles_root="$2"
    [[ -L "$target" ]] || return 0

    local link_dest abs_dest
    link_dest=$(readlink "$target")
    case "$link_dest" in
        /*) abs_dest="$link_dest" ;;
        *)  abs_dest="$(cd "$(dirname "$target")" 2>/dev/null && pwd)/$link_dest" ;;
    esac

    if [[ ! -e "$target" ]] || [[ "$abs_dest" == "$dotfiles_root"/* ]]; then
        echo "  Removed legacy dotfiles symlink: $target -> $link_dest"
        rm -f "$target"
    fi
}

migrate_legacy_chezmoi_symlinks() {
    local dotfiles_root="$1"
    migrate_legacy_symlink "$HOME/.gitconfig" "$dotfiles_root"
    migrate_legacy_symlink "$HOME/.copilot/mcp-config.json" "$dotfiles_root"
}

prepare_chezmoi_wiring() {
    local dotfiles_root="$1" source_dir="$2"
    local config_dir="$HOME/.config/chezmoi"
    local config_file="$config_dir/chezmoi.toml"
    local stale_stub=false
    export CHEZMOI_WIRING_SKIP=false

    bootstrap_chezmoi_linux || return 1
    migrate_legacy_chezmoi_symlinks "$dotfiles_root" || return 1

    if [[ -f "$config_file" ]] && ! grep -q '^\[data\]' "$config_file"; then
        stale_stub=true
    fi

    if $stale_stub; then
        if command -v chezmoi &>/dev/null && [[ -t 0 ]] && [[ -f "$source_dir/.chezmoi.toml.tmpl" ]]; then
            echo "  Detected stale chezmoi.toml stub (no [data]); re-running chezmoi init"
            rm -f "$config_file"
        else
            echo "  ERROR: chezmoi.toml has no [data] block — chezmoi apply will fail." >&2
            echo "  Re-run 'dots sync' from a real terminal to repopulate the prompts," >&2
            echo "  or delete $config_file and run 'chezmoi init --source $source_dir'." >&2
            return 1
        fi
    fi

    [[ -f "$config_file" ]] && return 0
    if ! command -v chezmoi &>/dev/null; then
        echo "  Skipping chezmoi setup (chezmoi not installed)"
        export CHEZMOI_WIRING_SKIP=true
        return 0
    fi

    mkdir -p "$config_dir"
    if [[ ! -t 0 ]] && [[ -f "$source_dir/.chezmoi.toml.tmpl" ]]; then
        echo "  ERROR: chezmoi.toml is missing and no TTY available to run init." >&2
        echo "  Re-run 'dots sync' (or 'chezmoi init --source $source_dir')" >&2
        echo "  from a real terminal so the first-time prompts can fire." >&2
        return 1
    fi

    if [[ -f "$source_dir/.chezmoi.toml.tmpl" ]]; then
        echo "  First-run chezmoi init (prompts for email and work-machine flag)"
        chezmoi init --source "$source_dir"
        echo "  Wrote chezmoi.toml from .chezmoi.toml.tmpl"
    else
        cat > "$config_file" <<EOF
# Generated by dots sync (chezmoi/.sync) on first setup.
sourceDir = "$source_dir"
EOF
        echo "  Wrote chezmoi.toml -> sourceDir=$source_dir (no template found)"
    fi
}

assemble_chezmoi_sources() {
    local dotfiles_root="$1" source_dir="$2"
    if ! sync_claude_chezmoi_sources "$dotfiles_root" "$source_dir"; then
        echo "  ERROR: claude chezmoi source assembly failed — aborting chezmoi apply" >&2
        return 1
    fi
    if ! sync_codex_chezmoi_sources "$dotfiles_root" "$source_dir"; then
        echo "  ERROR: codex chezmoi source assembly failed — aborting chezmoi apply" >&2
        return 1
    fi
    if ! sync_omp_chezmoi_sources "$dotfiles_root" "$source_dir"; then
        echo "  ERROR: OMP chezmoi source assembly failed — aborting chezmoi apply" >&2
        return 1
    fi
    if ! sync_pi_chezmoi_sources "$dotfiles_root" "$source_dir"; then
        echo "  ERROR: Pi chezmoi source assembly failed — aborting chezmoi apply" >&2
        return 1
    fi
}

# Land the tracked mise manifest before package convergence reads it.
#
# mise loads ~/.config/mise/config.toml *after* any --source manifest and lets
# it win, so convergence resolves the live pins rather than the tracked ones.
# Leaving that copy to the final apply deadlocks every pin bump: the stale file
# pins the old version, `mise install` therefore never requests the new one,
# and the harness-version gate — seeing the old binary — skips the very apply
# that would refresh it. The manifest is an input to convergence, not an
# output of it, so it has to land first.
apply_mise_manifest() {
    local source_dir="$1"
    local target="${XDG_CONFIG_HOME:-$HOME/.config}/mise/config.toml"
    command -v chezmoi &>/dev/null || return 0
    if chezmoi --source "$source_dir" apply --force "$target"; then
        echo "  Applied tracked mise manifest -> $target"
    else
        # Non-fatal: the harness-version gate stays the authority on whether
        # convergence actually produced the pinned harnesses.
        echo "  WARNING: could not apply $target — package convergence may read stale pins" >&2
    fi
}

apply_chezmoi_source() {
    local source_dir="$1" chezmoi_status=0
    if command -v chezmoi &>/dev/null; then
        if (set -o pipefail; chezmoi --source "$source_dir" apply --force 2>&1 | sed 's/^/  /'); then
            echo "  chezmoi apply complete"
        else
            chezmoi_status=$?
            echo "  ERROR: chezmoi apply failed (exit $chezmoi_status) — alphabetically-later run_onchange installers were skipped" >&2
            echo "         See the specific error above for the cause. Common ones:" >&2
            echo "           • settings.json unknown-key halt → fold the key into chezmoi/lib/claude-settings-authoritative.json or chezmoi/.chezmoidata/claude.yaml" >&2
            echo "           • 'gh auth status' failing → run 'gh auth login', then re-run 'dots sync'." >&2
        fi
    else
        echo "  Skipping chezmoi apply (chezmoi not installed); chezmoi-managed files will not sync"
    fi
    return "$chezmoi_status"
}

# Directory names that are never symlinked or dispatched to.
# Documented in the wiki (operations/sync-and-chezmoi.md) — keep in sync.
# `cursor` is skipped like `codex`: ~/.cursor is a real dir owned by chezmoi's
# install-cursor-plugin.sh + the ap cursor renderer, NOT a symlink to this repo
# (a whole-dir symlink leaked all of Cursor's runtime state back into dotfiles).
SYNC_SKIP_LIST=(".git" ".local" ".worktrees" "reference" "packages" "brew" "apt" "agents" "agent-profile" "codex" "cursor")

# Failure ledger — every .sync script that exits non-zero appends its name
# here. .sync inspects this at the end of run_sync, prints a
# summary, and exits non-zero so a partial sync doesn't masquerade as green.
SYNC_FAILURES=()

is_skipped() {
    local name="$1"
    local skip
    for skip in "${SYNC_SKIP_LIST[@]}"; do
        [[ "$name" == "$skip" ]] && return 0
    done
    return 1
}

# Parse run_sync arguments into exported env vars
parse_sync_args() {
    export DOTFILES_DEV=false

    while (( $# )); do
      case $1 in
         dev)
              echo "Setting dev=true"
              export DOTFILES_DEV=true
              ;;
         refresh|r)
              echo "Setting force_packages=true"
              export FORCE_PACKAGES=true
              ;;
      esac
      shift
    done
}


# True when $dir is a *linked* git worktree rather than the primary clone.
# Home-directory symlinks (~/.zshrc, ~/.zshenv, …) must only ever point at the
# primary clone: syncing from an ephemeral worktree (Conductor/ccw) repoints
# them at a path that dangles the moment the worktree is removed, silently
# breaking the shell — DOTFILES_DIR (derived from ~/.zshrc's resolved target)
# then points at a dead path, dropping bin/ off PATH. Fails open (returns
# non-linked) when git is unavailable or $dir is not a repo, so non-git
# deploys and the test harness are unaffected.
dir_is_linked_worktree() {
    local d="${1:-$dir}" gitdir common
    command -v git &>/dev/null || return 1
    gitdir=$(git -C "$d" rev-parse --absolute-git-dir 2>/dev/null) || return 1
    common=$(git -C "$d" rev-parse --path-format=absolute --git-common-dir 2>/dev/null) || return 1
    [[ "$gitdir" != "$common" ]]
}

# Symlink a single file/dir, or dispatch to its .sync script if present
sync_entry() {
    local file="$1"

    is_skipped "$file" && return 0

    # Directories with .sync scripts manage their own setup (e.g. claude/.sync
    # symlinks items INTO ~/.claude without replacing the whole directory)
    if [[ -d "$dir/$file" && -f "$dir/$file/.sync" ]]; then
        log_info "Running .sync for $file."
        if ! bash "$dir/$file/.sync"; then
            log_error "sync for $file FAILED (continuing — will report at end)"
            SYNC_FAILURES+=("$file")
        fi
        return 0
    fi

    # Guard against the worktree-hijack: never create (or destroy) a global home
    # symlink while syncing from a linked worktree. Removing the existing block
    # too is deliberate — otherwise we'd delete the good primary-pointing link
    # (line below) before bailing. Warn once, not per-file.
    if dir_is_linked_worktree; then
        if [[ "${_WORKTREE_SYMLINK_WARNED:-}" != "1" ]]; then
            log_warning "Skipping home symlinks: syncing from a linked git worktree ($dir)."
            log_warning "  Run 'dots sync' from the primary clone so ~/.zshrc etc. don't dangle when this worktree is removed."
            _WORKTREE_SYMLINK_WARNED=1
        fi
        return 0
    fi

    if [[ -h ~/."$file" ]]; then
        log_info "Removing old link to $file"
        rm ~/."$file"
    fi
    if [[ -f ~/."$file" || -d ~/."$file" ]]; then
        log_info "Moving existing $file from ~ to $olddir"
        rm -rf "$olddir/.$file" 2>/dev/null || true
        mv ~/."$file" "$olddir"
    fi

    log_info "Creating symlink to $file in home directory."
    ln -s "$dir/$file" ~/."$file"
}

# Dispatch hidden directories that own a .sync script (e.g. .copilot/).
# Globbing skips hidden dirs by default, so we iterate them explicitly.
sync_hidden_dirs() {
    local entry name
    for entry in "$dir"/.*/; do
        [[ -d "$entry" ]] || continue
        name="$(basename "$entry")"
        [[ "$name" == "." || "$name" == ".." ]] && continue
        is_skipped "$name" && continue
        [[ -f "$entry.sync" ]] || continue

        log_info "Running .sync for $name."
        if ! bash "$entry.sync"; then
            log_error "sync for $name FAILED (continuing — will report at end)"
            SYNC_FAILURES+=("$name")
        fi
    done
}

# Install TPM (tmux plugin manager) if not present, then run install_plugins
# on every sync — it's idempotent (skips already-installed plugins), so this
# also repairs machines where the plugin dir predates newly added plugins.
install_tpm() {
    command -v tmux &>/dev/null || return 0

    if [[ ! -d "$HOME/.tmux/plugins/tpm" ]]; then
        log_info "Installing TPM (tmux plugin manager)..."
        git clone https://github.com/tmux-plugins/tpm "$HOME/.tmux/plugins/tpm" 2>&1 | while read -r line; do
          log_info "  $line"
        done
    fi

    local install_plugins="$HOME/.tmux/plugins/tpm/bin/install_plugins"
    [[ -x "$install_plugins" ]] || return 0

    log_info "Installing tmux plugins..."
    "$install_plugins" 2>&1 | while read -r line; do
      log_info "  $line"
    done
}

# ── claude chezmoi source assembly ──────────────────────────────────────────
# sync_claude_chezmoi_sources <dotfiles_root> [<chezmoi_source_dir>]
#
# Assembles the registry-selected ~/.claude file payload into chezmoi source
# state as exact_ directories, so `chezmoi apply` DELETES anything live that
# is no longer selected (spec: chezmoi-authoritative-claude, decisions D1/G1).
#
#   dot_claude/exact_skills     ← skills/<name> per claude.yaml `skills`
#                                 + vendored external skills (skills/_registry.yaml)
#   dot_claude/exact_agents     ← agents/agent_definitions/<name>.md per
#                                 claude.yaml `agents`, frontmatter rendered
#                                 from agents/registry.yaml metadata
#   dot_claude/exact_commands   ← claude/commands
#   dot_claude/exact_hooks      ← claude/hooks + agents/hooks/*.sh
#   dot_claude/exact_lib        ← agents/lib
#   dot_claude/exact_reference  ← claude/reference + agents/reference
#   dot_claude/exact_workflows  ← claude/workflows
#
# The assembled trees are DERIVED state (gitignored); the repo dirs stay the
# single source of truth. Runs inside `dots sync` before `chezmoi apply`.

# Encode one path component for chezmoi source state.
#   _cz_encode_name <name> <is_dir> <is_executable>
_cz_encode_name() {
    local name="$1" is_dir="$2" is_exec="$3" prefix=""
    [[ "$is_dir" == true ]] && prefix+="exact_"
    [[ "$is_dir" != true && "$is_exec" == true ]] && prefix+="executable_"
    if [[ "$name" == .* ]]; then
        prefix+="dot_"
        name="${name#.}"
    fi
    # Escape a literal name that collides with a chezmoi attribute prefix.
    if [[ "$name" =~ ^(dot_|literal_|exact_|private_|readonly_|executable_|empty_|encrypted_|create_|modify_|remove_|symlink_|run_|once_|onchange_|before_|after_) ]]; then
        prefix+="literal_"
    fi
    printf '%s%s' "$prefix" "$name"
}

# Recursively copy a directory's CONTENTS into a chezmoi source dir, encoding
# every component. Symlinks are dereferenced; .git/.DS_Store are skipped.
# Fail-loud: a cp/mkdir failure propagates so a partial staging tree can never
# swap in (exact_ semantics would DELETE the missing live entries).
#   _cz_copy_encoded <src_dir> <dst_dir>
_cz_copy_encoded() {
    local src="$1" dst="$2" entry name enc
    mkdir -p "$dst" || return 1
    for entry in "$src"/* "$src"/.*; do
        [[ -e "$entry" || -L "$entry" ]] || continue
        name="$(basename "$entry")"
        [[ "$name" == "." || "$name" == ".." || "$name" == ".git" || "$name" == ".DS_Store" ]] && continue
        if [[ -d "$entry" ]]; then
            enc="$(_cz_encode_name "$name" true false)"
            _cz_copy_encoded "$entry" "$dst/$enc" || return 1
        elif [[ -f "$entry" ]]; then
            local is_exec=false
            [[ -x "$entry" ]] && is_exec=true
            enc="$(_cz_encode_name "$name" false "$is_exec")"
            if ! cp -L "$entry" "$dst/$enc"; then
                log_error "claude source assembly: copy failed: $entry"
                return 1
            fi
        else
            # Dangling symlink or special file: it can't be vendored, and
            # dropping it silently would delete the live copy on apply.
            log_warning "claude source assembly: skipping unreadable entry: $entry"
        fi
    done
    return 0
}

# Render one claude sub-agent file: YAML frontmatter from agents/registry.yaml
# metadata + the instruction body from body_path. Mirrors ap's claude renderer
# output shape (verified by diff against a live render).
#   _cz_render_claude_agent <registry_yaml> <name> <dotfiles_root> <out_file>
_cz_render_claude_agent() {
    local registry="$1" name="$2" root="$3" out="$4"
    local body_path
    body_path=$(yq -r ".agents.\"$name\".body_path // \"\"" "$registry")
    if [[ -z "$body_path" || ! -f "$root/$body_path" ]]; then
        log_error "claude agent '$name': body_path missing (registry: $registry)"
        return 1
    fi
    {
        echo "---"
        echo "name: $name"
        yq -o=json ".agents.\"$name\"" "$registry" | jq -r '
            def line(k; v): if v == null then empty else k + ": " + v end;
            line("description";     .description),
            line("tools";           (if .tools then (.tools | join(", ")) else null end)),
            line("disallowedTools"; (if .disallowedTools then "[" + (.disallowedTools | join(", ")) + "]" else null end)),
            line("model";           .models.claude),
            line("color";           .color),
            line("effort";          .effort),
            line("maxTurns";        (if .maxTurns then (.maxTurns | tostring) else null end)),
            line("skills";          (if .skills then "[" + (.skills | join(", ")) + "]" else null end))
        '
        echo "---"
        cat "$root/$body_path"
    } > "$out"
}

# Vendor external skills from skills/_registry.yaml into <dst>. Clones each
# source into a cache dir; offline falls back to the cached checkout with a
# warning. A source that has never been cloned and cannot be cloned fails the
# assembly (loud, per fail-fast). Unpinned sources float to latest of their
# default branch on every sync (offline → cached checkout); a pin change is
# always honored, an unchanged pin costs no network. Per-source `skills_path`
# (default "skills") relocates the in-repo skills dir the source is scanned
# under, for sources that bundle skills at a nested path (e.g. plugin repos).
_cz_vendor_external_skills() {
    local registry="$1" dst="$2" harness="$3"
    [[ -f "$registry" ]] || return 0
    local cache_root="${XDG_CACHE_HOME:-$HOME/.cache}/dotfiles/claude-skill-sources"
    mkdir -p "$cache_root"

    local source
    while IFS= read -r source; do
        [[ -z "$source" ]] && continue
        # Per-source harness filter: absent means every harness.
        local harnesses
        harnesses=$(yq -r ".sources.\"$source\".harnesses // [] | join(\" \")" "$registry")
        [[ -z "$harnesses" || " $harnesses " == *" $harness "* ]] || continue

        local pin cache sp
        pin=$(yq -r ".sources.\"$source\".pin // \"\"" "$registry")
        sp=$(yq -r ".sources.\"$source\".skills_path // \"skills\"" "$registry")
        # skills_path is interpolated into cache paths — reject values that
        # would escape the source's cache subtree (fail loud, per fail-fast).
        if [[ -z "$sp" || "$sp" == /* || "$sp" == *..* ]]; then
            log_error "external skill source $source: invalid skills_path '$sp' (must be relative, no '..')"
            return 1
        fi
        cache="$cache_root/${source//\//__}"

        if [[ ! -d "$cache/.git" ]]; then
            local -a clone_args=(clone --depth 1)
            [[ -n "$pin" ]] && clone_args+=(--branch "$pin")
            if ! git "${clone_args[@]}" "https://github.com/$source" "$cache"; then
                log_error "external skill source $source: clone failed and no cache exists"
                return 1
            fi
            [[ -n "$pin" ]] && echo "$pin" > "$cache/.dotfiles-pin"
        elif [[ -n "$pin" ]]; then
            # Honor a pin change on an existing cache (pin = branch or tag per
            # the registry schema). .dotfiles-pin records the checked-out pin
            # so an unchanged pin costs no network on the sync hot path.
            if [[ "$(cat "$cache/.dotfiles-pin" 2>/dev/null)" != "$pin" ]]; then
                if git -C "$cache" fetch --depth 1 origin "$pin" >/dev/null 2>&1 \
                    && git -C "$cache" checkout --detach FETCH_HEAD >/dev/null 2>&1; then
                    echo "$pin" > "$cache/.dotfiles-pin"
                else
                    log_error "external skill source $source: cannot check out pin '$pin'"
                    return 1
                fi
            fi
        else
            # Unpinned: float to latest of the default branch on every sync.
            # Offline (pull fails) falls back to the existing cached checkout.
            git -C "$cache" pull --ff-only >/dev/null 2>&1 \
                || log_warning "external skill source $source: pull failed, using cached checkout"
        fi

        # Explicit skill list, else every skills/<name>/SKILL.md in the source.
        local -a names=()
        local n
        while IFS= read -r n; do
            [[ -n "$n" && "$n" != "null" ]] && names+=("$n")
        done < <(yq -r ".sources.\"$source\".skills // [] | .[]" "$registry")
        if (( ${#names[@]} == 0 )); then
            local d
            for d in "$cache/$sp"/*/; do
                [[ -f "$d/SKILL.md" ]] && names+=("$(basename "$d")")
            done
        fi

        local skill
        for skill in "${names[@]:-}"; do
            [[ -z "$skill" ]] && continue
            if [[ ! -d "$cache/$sp/$skill" ]]; then
                log_warning "external skill source $source: skill '$skill' not found, skipping"
                continue
            fi
            _cz_copy_encoded "$cache/$sp/$skill" "$dst/$(_cz_encode_name "$skill" true false)" || return 1
        done
    done < <(yq -r '.sources | keys | .[]' "$registry")
}

sync_claude_chezmoi_sources() {
    local root="$1"
    local src="${2:-$root/chezmoi}"
    local claude_reg="$src/.chezmoidata/claude.yaml"

    if ! command -v yq &>/dev/null; then
        log_warning "yq not found — skipping claude chezmoi source assembly"
        return 0
    fi
    if [[ ! -f "$claude_reg" ]]; then
        log_error "claude registry not found: $claude_reg"
        return 1
    fi

    local staging
    staging=$(mktemp -d "${TMPDIR:-/tmp}/claude-cz-src.XXXXXX") || return 1
    # shellcheck disable=SC2064
    trap "rm -rf '$staging'" RETURN

    # skills — registry-selected local + vendored external
    local name
    while IFS= read -r name; do
        [[ -z "$name" ]] && continue
        if [[ ! -d "$root/skills/$name" ]]; then
            log_error "claude registry selects unknown skill: $name (no skills/$name)"
            return 1
        fi
        _cz_copy_encoded "$root/skills/$name" "$staging/exact_skills/$(_cz_encode_name "$name" true false)" || return 1
    done < <(yq -r '.claude.skills // [] | .[]' "$claude_reg")
    _cz_vendor_external_skills "$root/skills/_registry.yaml" "$staging/exact_skills" claude || return 1
    mkdir -p "$staging/exact_skills"

    # agents — rendered from agents/registry.yaml
    mkdir -p "$staging/exact_agents"
    while IFS= read -r name; do
        [[ -z "$name" ]] && continue
        _cz_render_claude_agent "$root/agents/registry.yaml" "$name" "$root" \
            "$staging/exact_agents/$name.md" || return 1
    done < <(yq -r '.claude.agents // [] | .[]' "$claude_reg")

    # commands / hooks / lib / reference / workflows
    _cz_copy_encoded "$root/claude/commands"  "$staging/exact_commands" || return 1
    _cz_copy_encoded "$root/claude/hooks"     "$staging/exact_hooks" || return 1
    # Registry hooks (agents/hooks/registry.yaml): copy the script of every
    # claude-harness entry (default harness set includes claude).
    local hook_scripts hook_script
    if ! hook_scripts=$(yq -r '.hooks[] | select(.script != null) | select([(.harnesses // ["claude", "codex"])[] == "claude"] | any) | .script' "$root/agents/hooks/registry.yaml"); then
        log_error "claude source assembly: reading hook registry ($root/agents/hooks/registry.yaml) failed — hook assembly aborted"
        return 1
    fi
    if [[ -n "$hook_scripts" ]]; then
        while IFS= read -r hook_script; do
            [[ -z "$hook_script" || "$hook_script" == "null" ]] && continue
            if [[ ! -f "$root/$hook_script" ]]; then
                log_error "hook registry references missing script: $hook_script"
                return 1
            fi
            if ! cp -L "$root/$hook_script" "$staging/exact_hooks/$(_cz_encode_name "$(basename "$hook_script")" false true)"; then
                log_error "claude source assembly: hook copy failed: $hook_script"
                return 1
            fi
        done <<<"$hook_scripts"
    fi
    _cz_copy_encoded "$root/agents/lib"       "$staging/exact_lib" || return 1
    _cz_copy_encoded "$root/claude/reference" "$staging/exact_reference" || return 1
    _cz_copy_encoded "$root/agents/reference" "$staging/exact_reference" || return 1
    _cz_copy_encoded "$root/claude/workflows" "$staging/exact_workflows" || return 1

    # Swap staged trees into the chezmoi source dir (all-or-nothing per dir).
    local tree
    for tree in exact_skills exact_agents exact_commands exact_hooks exact_lib exact_reference exact_workflows; do
        if ! rm -rf "${src:?}/dot_claude/$tree" \
            || ! mkdir -p "$src/dot_claude" \
            || ! mv "$staging/$tree" "$src/dot_claude/$tree"; then
            log_error "claude source assembly: staging swap failed for $tree — source state may be incomplete; rerun dots sync before chezmoi apply"
            return 1
        fi
    done
    log_info "Assembled claude chezmoi source state (dot_claude/exact_*)"
    return 0
}

# ── codex chezmoi source assembly ───────────────────────────────────────────
# sync_codex_chezmoi_sources <dotfiles_root> [<chezmoi_source_dir>]
#
# Assembles the registry-selected ~/.codex payload into chezmoi source state as
# exact_ directories, so `chezmoi apply` DELETES anything live that is no longer
# selected (spec: chezmoi-authoritative-codex). Mirrors
# sync_claude_chezmoi_sources.
#
#   private_dot_codex/exact_agents    ← agents/agent_definitions/<name>.md per
#                               codex.yaml `agents`, rendered to TOML from
#                               agents/registry.yaml metadata
#   private_dot_codex/exact_hooks     ← script of every codex-harness registry hook
#   private_dot_codex/exact_lib       ← those hooks' shared_assets under agents/lib
#   private_dot_codex/exact_reference ← those hooks' shared_assets under agents/reference
#   private_dot_codex/hooks.json      ← derived hook wiring
#
# config.toml is deliberately NOT assembled here: it carries Codex-CLI runtime
# state (projects trust, hooks.state hashes, marketplaces, plugins) that a
# wholesale rewrite would destroy, so private_dot_codex/modify_private_config.toml merges it in
# place instead.
#
# The assembled trees are DERIVED state (gitignored); the repo dirs stay the
# single source of truth. Runs inside `dots sync` before `chezmoi apply`.

# Render one codex sub-agent file as TOML. Field mapping mirrors ap's codex
# renderer (agent-profile/agent_profile/renderers/codex.py:129-159): name,
# description, optional model (models.codex), sandbox_mode="read-only" for
# read-only agents, then developer_instructions.
#
# The read-only predicate replicates agent_profile.shared.agent_is_read_only:
# read-only when NO write tool remains reachable — every write tool is either
# banned by disallowedTools or excluded by a tools whitelist. Banning `Write`
# alone must NOT imply read-only, or agents that write through
# mcp__tilth__tilth_write (coder, researcher, reviewer, explorer's overflow
# artifact) would be sandboxed out of their own job.
# tests/sync-codex-sources.bats asserts parity so the two copies cannot drift.
#   _cz_render_codex_agent <registry_yaml> <name> <dotfiles_root> <out_file>
_cz_render_codex_agent() {
    local registry="$1" name="$2" root="$3" out="$4"
    local body_path body
    body_path=$(yq -r ".agents.\"$name\".body_path // \"\"" "$registry") || return 1
    if [[ -z "$body_path" || "$body_path" == "null" || ! -f "$root/$body_path" ]]; then
        log_error "codex agent '$name': body_path missing (registry: $registry)"
        return 1
    fi
    body=$(cat "$root/$body_path") || return 1
    if ! yq -o=json ".agents.\"$name\"" "$registry" \
        | jq --arg name "$name" --arg body "$body" '
            def wt: ["Edit","Write","MultiEdit","NotebookEdit","mcp__tilth__tilth_write"];
            def covers($entry; $tool): ($entry == $tool)
                or (($entry | endswith("*")) and ($tool | startswith($entry[0:-1])));
            def available($tool; $tools; $dis):
                (($dis | any(covers(.; $tool))) | not)
                and (($tools | length) == 0 or ($tools | any(covers(.; $tool))));
            def read_only:
                ((.tools // [])) as $tools
                | ((.disallowedTools // [])) as $dis
                | (wt | any(available(.; $tools; $dis))) | not;
            { name: $name, description: (.description // "") }
            + (if (.models.codex // "") != "" then { model: .models.codex } else {} end)
            + (if read_only then { sandbox_mode: "read-only" } else {} end)
            + { developer_instructions: $body }
        ' \
        | yq -p=json -o=toml '.' > "$out"; then
        log_error "codex source assembly: rendering agent '$name' failed"
        return 1
    fi
    return 0
}

# Build ~/.codex/hooks.json from the codex-harness entries of the hook
# registry. Codex requires a JSON OBJECT with a top-level `hooks` map (event →
# matcher groups → command handlers); a flat array parses as JSON but Codex
# rejects it (see .hallouminate/wiki/harnesses/codex-hooks-schema.md).
# Commands are absolute: Codex runs hook commands from the session working
# directory, not from ~/.codex, so a relative path would never resolve.
#   _cz_codex_hooks_json <hook_registry_yaml> <deployed_hooks_dir>
_cz_codex_hooks_json() {
    local registry="$1" hooks_dir="$2"
    yq -o=json '.hooks' "$registry" | jq --arg dir "$hooks_dir" '
        to_entries
        | map(select([((.value.harnesses // ["claude","codex"])[]) == "codex"] | any))
        | map(.value)
        | map(select(.script != null))
        | group_by(.event)
        | map({ (.[0].event): [ .[] | {
                hooks: [ { type: "command",
                           command: ("bash " + $dir + "/" + (.script | split("/") | last)) }
                         + (if .timeout then { timeout: .timeout } else {} end) ] }
              + (if .matcher then { matcher: .matcher } else {} end) ] })
        | add
        | { hooks: (. // {}) }
    '
}

# Stage one hook shared_asset. Assets are declared repo-relative under agents/
# (e.g. agents/lib/git-guard.js); the deployed layout strips that prefix so the
# self-locating hook scripts resolve them (HARNESS_ROOT = ~/.codex). Every path
# component is chezmoi-encoded.
#   _cz_stage_codex_asset <dotfiles_root> <asset_rel_path> <staging_dir>
_cz_stage_codex_asset() {
    local root="$1" asset="$2" staging="$3"
    if [[ ! -f "$root/$asset" ]]; then
        log_error "hook registry references missing shared_asset: $asset"
        return 1
    fi
    local rest="${asset#agents/}"
    if [[ "$rest" == "$asset" ]]; then
        log_error "codex source assembly: shared_asset outside agents/: $asset"
        return 1
    fi
    # First component selects the tree (lib → exact_lib); the rest is nested.
    local tree="${rest%%/*}" remainder="${rest#*/}" dir enc comp
    dir="$staging/exact_$tree"
    while [[ "$remainder" == */* ]]; do
        comp="${remainder%%/*}"
        remainder="${remainder#*/}"
        enc="$(_cz_encode_name "$comp" true false)"
        dir="$dir/$enc"
    done
    mkdir -p "$dir" || return 1
    local is_exec=false
    [[ -x "$root/$asset" ]] && is_exec=true
    enc="$(_cz_encode_name "$remainder" false "$is_exec")"
    if ! cp -L "$root/$asset" "$dir/$enc"; then
        log_error "codex source assembly: shared_asset copy failed: $asset"
        return 1
    fi
    return 0
}

sync_codex_chezmoi_sources() {
    local root="$1" src="${2:-$1/chezmoi}"
    local codex_reg="$src/.chezmoidata/codex.yaml"
    local hook_reg="$root/agents/hooks/registry.yaml"

    if ! command -v yq >/dev/null 2>&1 || ! command -v jq >/dev/null 2>&1; then
        log_error "codex source assembly needs yq and jq — skipping would delete live ~/.codex state (exact_ semantics)"
        return 1
    fi
    if [[ ! -f "$codex_reg" ]]; then
        log_error "codex registry not found: $codex_reg"
        return 1
    fi
    if [[ ! -f "$hook_reg" ]]; then
        log_error "hook registry not found: $hook_reg"
        return 1
    fi

    local staging
    staging=$(mktemp -d "${TMPDIR:-/tmp}/codex-cz-src.XXXXXX") || return 1
    # shellcheck disable=SC2064
    trap "rm -rf '$staging'" RETURN

    # agents — rendered from agents/registry.yaml, validated against it
    local name harnesses
    mkdir -p "$staging/exact_agents"
    while IFS= read -r name; do
        [[ -z "$name" ]] && continue
        if [[ "$(yq -r ".agents | has(\"$name\")" "$root/agents/registry.yaml")" != "true" ]]; then
            log_error "codex registry selects unknown agent: $name (not in agents/registry.yaml)"
            return 1
        fi
        harnesses=$(yq -r ".agents.\"$name\" | [((.harnesses // [\"claude\",\"codex\"])[]) == \"codex\"] | any" \
            "$root/agents/registry.yaml")
        if [[ "$harnesses" != "true" ]]; then
            log_error "codex registry selects agent '$name', but its registry entry does not declare the codex harness"
            return 1
        fi
        _cz_render_codex_agent "$root/agents/registry.yaml" "$name" "$root" \
            "$staging/exact_agents/$name.toml" || return 1
    done < <(yq -r '.codex.agents // [] | .[]' "$codex_reg")

    # hooks — scripts + shared_assets of every codex-harness registry entry
    mkdir -p "$staging/exact_hooks" "$staging/exact_lib" "$staging/exact_reference"
    local hook_scripts hook_script
    if ! hook_scripts=$(yq -r '.hooks[] | select(.script != null) | select([((.harnesses // ["claude", "codex"])[]) == "codex"] | any) | .script' "$hook_reg"); then
        log_error "codex source assembly: reading hook registry ($hook_reg) failed — hook assembly aborted"
        return 1
    fi
    if [[ -n "$hook_scripts" ]]; then
        while IFS= read -r hook_script; do
            [[ -z "$hook_script" || "$hook_script" == "null" ]] && continue
            if [[ ! -f "$root/$hook_script" ]]; then
                log_error "hook registry references missing script: $hook_script"
                return 1
            fi
            if ! cp -L "$root/$hook_script" "$staging/exact_hooks/$(_cz_encode_name "$(basename "$hook_script")" false true)"; then
                log_error "codex source assembly: hook copy failed: $hook_script"
                return 1
            fi
        done <<<"$hook_scripts"
    fi

    local asset
    while IFS= read -r asset; do
        [[ -z "$asset" || "$asset" == "null" ]] && continue
        _cz_stage_codex_asset "$root" "$asset" "$staging" || return 1
    done < <(yq -r '.hooks[] | select([((.harnesses // ["claude", "codex"])[]) == "codex"] | any) | (.shared_assets // [])[]' "$hook_reg")

    # hooks.json — derived wiring, absolute command paths
    if ! _cz_codex_hooks_json "$hook_reg" "$HOME/.codex/hooks" > "$staging/hooks.json"; then
        log_error "codex source assembly: building hooks.json failed"
        return 1
    fi

    # Swap staged trees into the chezmoi source dir (all-or-nothing per dir).
    local tree
    for tree in exact_agents exact_hooks exact_lib exact_reference; do
        if ! rm -rf "${src:?}/private_dot_codex/$tree" \
            || ! mkdir -p "$src/private_dot_codex" \
            || ! mv "$staging/$tree" "$src/private_dot_codex/$tree"; then
            log_error "codex source assembly: staging swap failed for $tree — source state may be incomplete; rerun dots sync before chezmoi apply"
            return 1
        fi
    done
    if ! mv "$staging/hooks.json" "$src/private_dot_codex/hooks.json"; then
        log_error "codex source assembly: staging swap failed for hooks.json"
        return 1
    fi
    log_info "Assembled codex chezmoi source state (private_dot_codex/exact_*, hooks.json)"
    return 0
}

# Assemble the OMP-native global skills payload from the same selected sources
# as Claude. OMP discovers ~/.omp/agent/skills independently; it never reads
# ~/.agents/skills or ~/.claude/skills.
#   sync_omp_chezmoi_sources <dotfiles_root> [<chezmoi_source_dir>]
sync_omp_chezmoi_sources() {
    local root="$1"
    local src="${2:-$root/chezmoi}"
    local claude_reg="$src/.chezmoidata/claude.yaml"

    if ! command -v yq &>/dev/null; then
        log_warning "yq not found — skipping OMP chezmoi source assembly"
        return 0
    fi
    if [[ ! -f "$claude_reg" ]]; then
        log_error "claude registry not found: $claude_reg"
        return 1
    fi

    local staging
    staging=$(mktemp -d "${TMPDIR:-/tmp}/omp-cz-src.XXXXXX") || return 1
    # shellcheck disable=SC2064
    trap "rm -rf '$staging'" RETURN

    local name
    while IFS= read -r name; do
        [[ -z "$name" ]] && continue
        if [[ ! -d "$root/skills/$name" ]]; then
            log_error "OMP skill selection references unknown skill: $name (no skills/$name)"
            return 1
        fi
        _cz_copy_encoded "$root/skills/$name" "$staging/exact_skills/$(_cz_encode_name "$name" true false)" || return 1
    done < <(yq -r '.claude.skills // [] | .[]' "$claude_reg")
    _cz_vendor_external_skills "$root/skills/_registry.yaml" "$staging/exact_skills" omp || return 1
    mkdir -p "$staging/exact_skills"

    if ! rm -rf "${src:?}/dot_omp/private_agent/exact_skills" \
        || ! mkdir -p "$src/dot_omp/private_agent" \
        || ! mv "$staging/exact_skills" "$src/dot_omp/private_agent/exact_skills"; then
        log_error "OMP source assembly: staging swap failed for exact_skills — source state may be incomplete; rerun dots sync before chezmoi apply"
        return 1
    fi
    log_info "Assembled OMP chezmoi source state (dot_omp/private_agent/exact_skills)"
    return 0
}

# Assemble upstream Pi's global skills and shared Pi-family resources.
# Pi discovers these under ~/.pi/agent independently of OMP.
#   sync_pi_chezmoi_sources <dotfiles_root> [<chezmoi_source_dir>]
sync_pi_chezmoi_sources() {
    local root="$1"
    local src="${2:-$root/chezmoi}"
    local claude_reg="$src/.chezmoidata/claude.yaml"
    local omp_agent="$src/dot_omp/private_agent"

    if ! command -v yq &>/dev/null; then
        log_warning "yq not found — skipping Pi chezmoi source assembly"
        return 0
    fi
    if [[ ! -f "$claude_reg" ]]; then
        log_error "claude registry not found: $claude_reg"
        return 1
    fi

    local staging
    staging=$(mktemp -d "${TMPDIR:-/tmp}/pi-cz-src.XXXXXX") || return 1
    # shellcheck disable=SC2064
    trap "rm -rf '$staging'" RETURN

    local name
    while IFS= read -r name; do
        [[ -z "$name" ]] && continue
        if [[ ! -d "$root/skills/$name" ]]; then
            log_error "Pi skill selection references unknown skill: $name (no skills/$name)"
            return 1
        fi
        _cz_copy_encoded "$root/skills/$name" "$staging/exact_skills/$(_cz_encode_name "$name" true false)" || return 1
    done < <(yq -r '.claude.skills // [] | .[]' "$claude_reg")
    _cz_vendor_external_skills "$root/skills/_registry.yaml" "$staging/exact_skills" pi || return 1

    mkdir -p "$staging/exact_skills" "$staging/extensions" "$staging/themes"
    cp "$omp_agent/extensions/rtk.ts" "$omp_agent/extensions/cheese-flair.ts" \
        "$staging/extensions/" || return 1
    cp "$omp_agent/themes/chocolate-donut.json" "$staging/themes/" || return 1

    local tree
    for tree in exact_skills extensions themes; do
        if ! rm -rf "${src:?}/dot_pi/private_agent/$tree" \
            || ! mkdir -p "$src/dot_pi/private_agent" \
            || ! mv "$staging/$tree" "$src/dot_pi/private_agent/$tree"; then
            log_error "Pi source assembly: staging swap failed for $tree"
            return 1
        fi
    done
    rm -rf "$src/dot_pi/private_agent/exact_extensions" \
        "$src/dot_pi/private_agent/exact_themes"
    log_info "Assembled Pi chezmoi source state (skills, extensions, themes)"
}

# Reconcile OMP marketplace plugins and pinned npm plugins against the
# `.omp.plugins` and `.omp.npmPlugins` subtrees of
# chezmoi/.chezmoidata/omp.yaml. Runs after chezmoi apply so the mcp.json
# cutover (context7 only) lands with the plugin-owned MCP servers that replace
# it. Idempotent: a converged state makes zero `omp` mutating calls. Marketplace
# entries are exact-owned; unrelated npm plugins are preserved.
#   sync_omp_plugins <dotfiles_root>
sync_omp_plugins() {
    local root="$1"
    local reg="$root/chezmoi/.chezmoidata/omp.yaml"

    if ! command -v omp &>/dev/null; then
        log_warning "omp not found — skipping OMP plugin reconcile"
        return 0
    fi
    if ! command -v yq &>/dev/null; then
        log_warning "yq not found — skipping OMP plugin reconcile"
        return 0
    fi
    if ! command -v jq &>/dev/null; then
        log_warning "jq not found — skipping OMP plugin reconcile"
        return 0
    fi
    if [[ ! -f "$reg" ]]; then
        log_error "omp registry not found: $reg"
        return 1
    fi

    log_info "Reconciling OMP native plugins..."

    # Desired marketplace plugins: name\tmarketplace\tsource.
    local desired
    desired=$(yq -r '.omp.plugins // {} | to_entries | .[] | select(.value.marketplace and .value.source) | [.key, .value.marketplace, .value.source] | @tsv' "$reg")

    # Desired npm plugins: package\tversion.
    local desired_npm
    desired_npm=$(yq -r '.omp.npmPlugins // {} | to_entries | .[] | [.key, .value] | @tsv' "$reg")

    local desired_marketplaces
    desired_marketplaces=$(printf '%s\n' "$desired" | awk -F'\t' 'NF{print $2}' | sort -u)

    # Current marketplaces (empty if the file doesn't exist yet). Guarded:
    # under the caller's `set -e`, an unguarded jq failure on a malformed
    # file would abort the whole sync with no diagnostic.
    local current_marketplaces=""
    if [[ -f "$HOME/.omp/marketplaces.json" ]]; then
        if ! current_marketplaces=$(jq -r '.marketplaces[].name' "$HOME/.omp/marketplaces.json" 2>/dev/null); then
            log_warning "  ~/.omp/marketplaces.json malformed or missing .marketplaces — treating as none"
            current_marketplaces=""
        fi
    fi

    local plugin_state
    plugin_state=$(omp plugin list --json 2>/dev/null) || plugin_state='{}'

    # Current marketplace-installed plugin ids (e.g. "milknado@milknado").
    local current_installed
    current_installed=$(jq -r '.marketplace[]?.id' <<<"$plugin_state" 2>/dev/null) || current_installed=""

    # Current npm plugin package/version pairs.
    local current_npm
    current_npm=$(jq -r '
        .npm[]? | [.name, .version] | @tsv
    ' <<<"$plugin_state" 2>/dev/null) || current_npm=""

    # --- Additions: marketplace add, then plugin install ---------------
    local name marketplace source
    while IFS=$'\t' read -r name marketplace source; do
        [[ -z "$name" ]] && continue

        if ! grep -qxF "$marketplace" <<<"$current_marketplaces"; then
            log_info "  Adding OMP marketplace: $source"
            if ! omp plugin marketplace add "$source" >/dev/null 2>&1; then
                log_error "omp plugin marketplace add $source failed"
                return 1
            fi
            current_marketplaces=$(printf '%s\n%s' "$current_marketplaces" "$marketplace")
        fi

        if ! grep -qxF "${name}@${marketplace}" <<<"$current_installed"; then
            log_info "  Installing OMP plugin: ${name}@${marketplace}"
            if ! omp plugin install "${name}@${marketplace}" >/dev/null 2>&1; then
                log_error "omp plugin install ${name}@${marketplace} failed"
                return 1
            fi
        fi
    done <<<"$desired"

    # --- Pinned npm plugins: install missing packages and exact upgrades ---
    local package version
    while IFS=$'\t' read -r package version; do
        [[ -z "$package" ]] && continue
        if ! grep -qxF "$package"$'\t'"$version" <<<"$current_npm"; then
            log_info "  Installing OMP npm plugin: ${package}@${version}"
            if ! omp plugin install "${package}@${version}" >/dev/null 2>&1; then
                log_error "omp plugin install ${package}@${version} failed"
                return 1
            fi
        fi
    done <<<"$desired_npm"

    # --- Removals: uninstall plugins, then remove marketplaces no longer
    # referenced by any registry entry. Restricted to marketplace-sourced
    # ids (never touches `.npm`). ---------------------------------------
    local id
    while IFS= read -r id; do
        [[ -z "$id" ]] && continue
        if ! printf '%s\n' "$desired" | awk -F'\t' -v id="$id" '$1"@"$2 == id {found=1} END{exit !found}'; then
            log_info "  Uninstalling OMP plugin no longer in registry: $id"
            if ! omp plugin uninstall "$id" >/dev/null 2>&1; then
                log_error "omp plugin uninstall $id failed"
                return 1
            fi
        fi
    done <<<"$current_installed"

    local mp
    while IFS= read -r mp; do
        [[ -z "$mp" ]] && continue
        if ! grep -qxF "$mp" <<<"$desired_marketplaces"; then
            log_info "  Removing OMP marketplace no longer in registry: $mp"
            if ! omp plugin marketplace remove "$mp" >/dev/null 2>&1; then
                log_error "omp plugin marketplace remove $mp failed"
                return 1
            fi
        fi
    done <<<"$current_marketplaces"

    return 0
}

# Reconcile the pinned Pi extension packages declared in settings.json after
# chezmoi has authored that file. Pinned npm specs do not float on updates.
sync_pi_packages() {
    if ! command -v pi &>/dev/null; then
        log_warning "pi not found — skipping Pi package reconcile"
        return 0
    fi
    log_info "Reconciling Pi packages"
    if ! pi update --extensions; then
        log_error "Pi package reconcile failed"
        return 1
    fi
}

# Install prek pre-commit hooks (clears conflicting core.hooksPath first)
install_prek_hooks() {
    if ! command -v prek &>/dev/null; then
        log_warning "prek not installed, skipping pre-commit hooks"
        return 0
    fi

    if git config --local core.hooksPath &>/dev/null; then
      log_info "Unsetting local core.hooksPath (conflicts with prek)..."
      git config --local --unset core.hooksPath
    fi
    log_info "Installing prek pre-commit hooks..."
    prek install 2>&1 | while read -r line; do
      log_info "  $line"
    done
}

# Install tilth's claude-code integration (edit-mode MCP entry). tilth retired
# the inject-cwd.js PreToolUse hook, so no hook script is dropped or checked.
install_tilth_claude_code() {
    if ! command -v tilth &>/dev/null; then
        log_warning "tilth not installed, skipping claude-code install"
        return 0
    fi
    log_info "Installing tilth claude-code integration (tilth install claude-code --edit)..."
    tilth install claude-code --edit 2>&1 | while read -r line; do
        log_info "  $line"
    done
}


# Re-reconcile user-scope claude MCPs as the FINAL write of every sync.
#
# WHY unconditional (unlike the hash-gated run_onchange reconcile):
# install_tilth_claude_code runs `tilth install claude-code`, which rewrites the
# tilth entry in ~/.claude.json with tilth's OWN defaults (no --edit, no env,
# absolute command path) — clobbering the registry-authoritative shape. The
# chezmoi run_onchange reconcile only fires when the registry `mcps` hash
# changes, so it can't heal this. Running the reconcile here restores the
# registry shape after every tilth install. It's idempotent, so already-correct
# entries are no-ops.
reconcile_claude_mcps() {
    local lib="$dir/chezmoi/lib/claude-mcp-reconcile.sh"
    if ! command -v claude &>/dev/null || ! command -v yq &>/dev/null || [[ ! -f "$lib" ]]; then
        log_warning "Skipping claude MCP reconcile (claude, yq, or reconcile lib missing)"
        return 0
    fi

    log_info "Reconciling claude MCPs (restore registry shape after tilth install)..."
    # shellcheck source=chezmoi/lib/claude-mcp-reconcile.sh
    source "$lib"

    local mcps_json
    mcps_json=$(yq -o=json '.claude.mcps' "$dir/chezmoi/.chezmoidata/claude.yaml")

    claude_mcp_reconcile \
        "$mcps_json" \
        "$HOME/.claude.json" \
        "$HOME/.claude/.chezmoi-mcp-manifest" 2>&1 | while read -r line; do
        log_info "  $line"
    done
}
