#!/bin/bash
# theme/generate.sh - Generate all color targets from base24 YAML scheme
# Source of truth: theme/schemes/<name>.yaml
# Targets: zsh/colors.zsh, vimrc highlights, iterm2 plist, bin/colors
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_DIR="$(dirname "$SCRIPT_DIR")"

GREEN='\033[0;32m'
BLUE='\033[0;34m'
RED='\033[0;31m'
NC='\033[0m'

log_info()  { echo -e "${BLUE}[theme]${NC} $1"; }
log_ok()    { echo -e "${GREEN}[theme]${NC} $1"; }
log_err()   { echo -e "${RED}[theme]${NC} $1" >&2; }

if ! command -v yq &>/dev/null; then
  log_err "yq not found — install with: sudo snap install yq, or brew install yq"
  exit 1
fi

# Portable in-place sed (GNU vs BSD)
sedi() {
  if [[ "$(uname)" == "Darwin" ]]; then
    sed -i '' "$@"
  else
    sed -i "$@"
  fi
}

# ---------------------------------------------------------------------------
# Read config
# ---------------------------------------------------------------------------
ACTIVE=$(yq -r '.active-scheme' "$SCRIPT_DIR/config.yaml")
SCHEME_FILE="$SCRIPT_DIR/schemes/${ACTIVE}.yaml"

if [[ ! -f "$SCHEME_FILE" ]]; then
  log_err "Scheme file not found: $SCHEME_FILE"
  exit 1
fi

SCHEME_NAME=$(yq -r '.name' "$SCHEME_FILE")
SCHEME_DESC=$(yq -r '.description' "$SCHEME_FILE")
log_info "Active scheme: $SCHEME_NAME ($ACTIVE)"

# ---------------------------------------------------------------------------
# Read palette into individual variables (bash 3 compatible)
# ---------------------------------------------------------------------------
SLOTS="base00 base01 base02 base03 base04 base05 base06 base07 base08 base09 base0A base0B base0C base0D base0E base0F base10 base11 base12 base13 base14 base15 base16 base17"

for slot in $SLOTS; do
  eval "PAL_${slot}=$(yq -r ".palette.${slot}" "$SCHEME_FILE")"
done

# Helper to get palette value by slot name
pal() { eval "echo \$PAL_$1"; }

# ---------------------------------------------------------------------------
# Hex helpers
# ---------------------------------------------------------------------------
hex_r() { printf '%d' "0x${1:0:2}"; }
hex_g() { printf '%d' "0x${1:2:2}"; }
hex_b() { printf '%d' "0x${1:4:2}"; }

# Convert 6-digit hex to nearest xterm-256 color index
hex_to_256() {
  local hex="$1"
  local r g b
  r=$(hex_r "$hex"); g=$(hex_g "$hex"); b=$(hex_b "$hex")

  local best_idx=16
  local best_dist=$(( r*r + g*g + b*b ))

  # 6x6x6 color cube (indices 16-231)
  local ri gi bi cr cg cb d
  for ri in 0 1 2 3 4 5; do
    if [ $ri -eq 0 ]; then cr=0; else cr=$(( 55 + 40 * ri )); fi
    for gi in 0 1 2 3 4 5; do
      if [ $gi -eq 0 ]; then cg=0; else cg=$(( 55 + 40 * gi )); fi
      for bi in 0 1 2 3 4 5; do
        if [ $bi -eq 0 ]; then cb=0; else cb=$(( 55 + 40 * bi )); fi
        d=$(( (r-cr)*(r-cr) + (g-cg)*(g-cg) + (b-cb)*(b-cb) ))
        if [ $d -lt $best_dist ]; then
          best_dist=$d
          best_idx=$(( 16 + 36*ri + 6*gi + bi ))
        fi
      done
    done
  done

  # Grayscale ramp (232-255)
  local i cv
  for i in $(seq 0 23); do
    cv=$(( 8 + 10 * i ))
    d=$(( (r-cv)*(r-cv) + (g-cv)*(g-cv) + (b-cv)*(b-cv) ))
    if [ $d -lt $best_dist ]; then
      best_dist=$d
      best_idx=$(( 232 + i ))
    fi
  done

  echo $best_idx
}

# ---------------------------------------------------------------------------
# Precompute 256-color indices
# ---------------------------------------------------------------------------
for slot in $SLOTS; do
  eval "C256_${slot}=$(hex_to_256 "$(pal "$slot")")"
done

# Helper to get 256 value by slot name
c256() { eval "echo \$C256_$1"; }

log_info "Computed 256-color approximations"

# ---------------------------------------------------------------------------
# Generate zsh/colors.zsh
# ---------------------------------------------------------------------------
generate_colors_zsh() {
  local out="$REPO_DIR/zsh/colors.zsh"
  cat > "$out" <<COLORS
# ${SCHEME_NAME} - Shell Color Palette
# Generated by theme/generate.sh from theme/schemes/${ACTIVE}.yaml
# DO NOT EDIT - changes will be overwritten on next \`dots sync\`
#
# Background: #$(pal base00)
# Description: ${SCHEME_DESC}

# =============================================================================
# PALETTE DEFINITION
# =============================================================================

# -----------------------------------------------------------------------------
# Background / Foreground
# -----------------------------------------------------------------------------
__SDW_BG="#$(pal base00)"
__SDW_BG_256=$(c256 base00)

__SDW_BG_ALT="#$(pal base01)"
__SDW_BG_ALT_256=$(c256 base01)

__SDW_BG_HIGHLIGHT="#$(pal base02)"
__SDW_BG_HIGHLIGHT_256=$(c256 base02)

__SDW_DIM="#$(pal base03)"
__SDW_DIM_256=$(c256 base03)

__SDW_FG="#$(pal base05)"
__SDW_FG_256=$(c256 base05)

__SDW_FG_BRIGHT="#$(pal base07)"
__SDW_FG_BRIGHT_256=$(c256 base07)

# -----------------------------------------------------------------------------
# Accent Colors
# -----------------------------------------------------------------------------

# Red (errors)
__SDW_RED="#$(pal base08)"
__SDW_RED_256=$(c256 base08)

# Green (success)
__SDW_GREEN="#$(pal base0B)"
__SDW_GREEN_256=$(c256 base0B)

# Yellow (types, highlights)
__SDW_YELLOW="#$(pal base0A)"
__SDW_YELLOW_256=$(c256 base0A)

# Blue (functions)
__SDW_BLUE="#$(pal base0D)"
__SDW_BLUE_256=$(c256 base0D)

# Magenta (constants, keywords)
__SDW_MAGENTA="#$(pal base0E)"
__SDW_MAGENTA_256=$(c256 base0E)

# Cyan (strings)
__SDW_CYAN="#$(pal base0C)"
__SDW_CYAN_256=$(c256 base0C)

# -----------------------------------------------------------------------------
# Bright Variants
# -----------------------------------------------------------------------------
__SDW_BR_RED="#$(pal base12)"
__SDW_BR_RED_256=$(c256 base12)

__SDW_BR_GREEN="#$(pal base14)"
__SDW_BR_GREEN_256=$(c256 base14)

__SDW_BR_YELLOW="#$(pal base09)"
__SDW_BR_YELLOW_256=$(c256 base09)

__SDW_BR_BLUE="#$(pal base16)"
__SDW_BR_BLUE_256=$(c256 base16)

__SDW_BR_MAGENTA="#$(pal base17)"
__SDW_BR_MAGENTA_256=$(c256 base17)

__SDW_BR_CYAN="#$(pal base15)"
__SDW_BR_CYAN_256=$(c256 base15)

# =============================================================================
# ANSI 16-COLOR MAPPING
# =============================================================================
# Standard terminal color slots

__SDW_BLACK="\$__SDW_BG_ALT"
__SDW_BLACK_256=\$__SDW_BG_ALT_256

__SDW_WHITE="\$__SDW_FG"
__SDW_WHITE_256=\$__SDW_FG_256

__SDW_BR_BLACK="\$__SDW_DIM"
__SDW_BR_BLACK_256=\$__SDW_DIM_256

__SDW_BR_WHITE="\$__SDW_FG_BRIGHT"
__SDW_BR_WHITE_256=\$__SDW_FG_BRIGHT_256

# =============================================================================
# SEMANTIC ALIASES
# =============================================================================
__SDW_ERROR="\$__SDW_RED"
__SDW_SUCCESS="\$__SDW_GREEN"
__SDW_WARNING="\$__SDW_YELLOW"
__SDW_INFO="\$__SDW_CYAN"

__SDW_COMMENT="\$__SDW_DIM"
__SDW_STRING="\$__SDW_CYAN"
__SDW_KEYWORD="\$__SDW_MAGENTA"
__SDW_FUNCTION="\$__SDW_BLUE"
__SDW_TYPE="\$__SDW_YELLOW"
__SDW_CONSTANT="\$__SDW_MAGENTA"

# =============================================================================
# FZF COLOR STRING
# =============================================================================
__SDW_FZF_COLORS="--color=bg:\${__SDW_BG},bg+:\${__SDW_BG_ALT}"
__SDW_FZF_COLORS+=" --color=fg:\${__SDW_FG},fg+:\${__SDW_FG_BRIGHT}"
__SDW_FZF_COLORS+=" --color=hl:\${__SDW_CYAN},hl+:\${__SDW_BR_CYAN}"
__SDW_FZF_COLORS+=" --color=info:\${__SDW_DIM},marker:\${__SDW_GREEN}"
__SDW_FZF_COLORS+=" --color=pointer:\${__SDW_RED},prompt:\${__SDW_BLUE}"
__SDW_FZF_COLORS+=" --color=spinner:\${__SDW_MAGENTA},header:\${__SDW_MAGENTA}"

# =============================================================================
# LS_COLORS
# =============================================================================
export LS_COLORS='di=34:ln=36:so=35:pi=33:ex=32:bd=33;40:cd=33;40:su=31;40:sg=31;40:tw=34;40:ow=34;40:*.tar=31:*.tgz=31:*.zip=31:*.gz=31:*.bz2=31:*.7z=31:*.rar=31:*.jpg=35:*.jpeg=35:*.png=35:*.gif=35:*.svg=35:*.mp3=35:*.mp4=35:*.avi=35:*.mov=35:*.pdf=33:*.doc=33:*.docx=33:*.xls=33:*.xlsx=33:*.ppt=33:*.pptx=33:*.md=36:*.txt=37:*.json=33:*.xml=33:*.yaml=33:*.yml=33:*.toml=33:*.ini=33:*.conf=33:*.sh=32:*.bash=32:*.zsh=32:*.py=32:*.rb=32:*.js=32:*.ts=32:*.go=32:*.rs=32:*.c=32:*.cpp=32:*.h=32:*.hpp=32:*.java=32:*.vim=32:*.lua=32'

# BSD/macOS ls colors
export LSCOLORS='ExGxFxdxCxDxDxhbadacec'

# =============================================================================
# EXPORTS
# =============================================================================
export __SDW_BG __SDW_BG_ALT __SDW_FG __SDW_FG_BRIGHT __SDW_DIM
export __SDW_RED __SDW_GREEN __SDW_YELLOW __SDW_BLUE __SDW_MAGENTA __SDW_CYAN
export __SDW_BR_RED __SDW_BR_GREEN __SDW_BR_YELLOW __SDW_BR_BLUE __SDW_BR_MAGENTA __SDW_BR_CYAN
export __SDW_FZF_COLORS

# =============================================================================
# BACKWARD COMPATIBILITY (alias old __DW_* names)
# =============================================================================
__DW_BG="\$__SDW_BG"
__DW_BG_256=\$__SDW_BG_256
__DW_BG_ALT="\$__SDW_BG_ALT"
__DW_BG_ALT_256=\$__SDW_BG_ALT_256
__DW_FG="\$__SDW_FG"
__DW_FG_256=\$__SDW_FG_256
__DW_DIM="\$__SDW_DIM"
__DW_DIM_256=\$__SDW_DIM_256
__DW_BLUE="\$__SDW_BLUE"
__DW_BLUE_256=\$__SDW_BLUE_256
__DW_FZF_COLORS="\$__SDW_FZF_COLORS"
COLORS
  log_ok "Generated zsh/colors.zsh"
}

# ---------------------------------------------------------------------------
# Generate vimrc highlights
# ---------------------------------------------------------------------------
generate_vimrc() {
  local vimrc="$REPO_DIR/vimrc"
  local bg bg_alt bg_hl dim fg fg_bright red green yellow blue magenta cyan br_yellow
  bg=$(c256 base00); bg_alt=$(c256 base01); bg_hl=$(c256 base02)
  dim=$(c256 base03); fg=$(c256 base05); fg_bright=$(c256 base07)
  red=$(c256 base08); green=$(c256 base0B); yellow=$(c256 base0A)
  blue=$(c256 base0D); magenta=$(c256 base0E); cyan=$(c256 base0C)
  br_yellow=$(c256 base09)

  # Update header comments
  sedi "s/^\" Vim configuration with .* theme/\" Vim configuration with ${SCHEME_NAME} theme/" "$vimrc"
  sedi "s/^\" .* color scheme$/\" ${SCHEME_NAME} color scheme/" "$vimrc"
  sedi "s/^\" These colors match your terminal's .* theme$/\" These colors match your terminal's ${SCHEME_NAME} theme/" "$vimrc"
  sedi "s/^\" .*color definitions$/\" ${SCHEME_NAME} color definitions/" "$vimrc"
  sedi "s/^\" Using terminal colors that match .*$/\" Using terminal colors that match ${SCHEME_NAME}/" "$vimrc"

  # Helper: replace highlight line
  hl() {
    local name="$1"; shift
    sedi "s/^highlight ${name} .*$/highlight ${name} $*/" "$vimrc"
  }

  hl Normal        "ctermfg=$fg ctermbg=NONE"
  hl Comment       "ctermfg=$dim"
  hl Constant      "ctermfg=$br_yellow"
  hl String        "ctermfg=$green"
  hl Character     "ctermfg=$green"
  hl Number        "ctermfg=$br_yellow"
  hl Boolean       "ctermfg=$br_yellow"
  hl Float         "ctermfg=$br_yellow"
  hl Identifier    "ctermfg=$blue"
  hl Function      "ctermfg=$blue"
  hl Statement     "ctermfg=$magenta"
  hl Conditional   "ctermfg=$magenta"
  hl Repeat        "ctermfg=$magenta"
  hl Label         "ctermfg=$magenta"
  hl Operator      "ctermfg=$magenta"
  hl Keyword       "ctermfg=$magenta"
  hl Exception     "ctermfg=$magenta"
  hl PreProc       "ctermfg=$yellow"
  hl Include       "ctermfg=$yellow"
  hl Define        "ctermfg=$yellow"
  hl Macro         "ctermfg=$yellow"
  hl PreCondit     "ctermfg=$yellow"
  hl Type          "ctermfg=$yellow"
  hl StorageClass  "ctermfg=$yellow"
  hl Structure     "ctermfg=$yellow"
  hl Typedef       "ctermfg=$yellow"
  hl Special       "ctermfg=$red"
  hl SpecialChar   "ctermfg=$red"
  hl Tag           "ctermfg=$red"
  hl Delimiter     "ctermfg=$red"
  hl SpecialComment "ctermfg=$red"
  hl Debug         "ctermfg=$red"
  hl Underlined    "ctermfg=$blue cterm=underline"
  hl Error         "ctermfg=$fg_bright ctermbg=$red"
  hl Todo          "ctermfg=$bg ctermbg=$yellow"
  hl CursorLine    "cterm=NONE ctermbg=$bg_alt"
  hl CursorLineNr  "ctermfg=$yellow ctermbg=$bg_alt"
  hl LineNr        "ctermfg=$dim ctermbg=NONE"
  hl Visual        "ctermbg=$bg_hl"
  hl Search        "ctermfg=$bg ctermbg=$yellow"
  hl IncSearch     "ctermfg=$bg ctermbg=$cyan"
  hl StatusLine    "ctermfg=$fg ctermbg=$bg_hl"
  hl StatusLineNC  "ctermfg=$dim ctermbg=$bg_alt"
  hl VertSplit     "ctermfg=$bg_hl ctermbg=NONE"
  hl Pmenu         "ctermfg=$fg ctermbg=$bg_alt"
  hl PmenuSel      "ctermfg=$bg ctermbg=$yellow"
  hl Directory     "ctermfg=$blue"
  hl Folded        "ctermfg=$dim ctermbg=$bg_alt"
  hl FoldColumn    "ctermfg=$dim ctermbg=NONE"

  log_ok "Patched vimrc highlights"
}

# ---------------------------------------------------------------------------
# Patch iTerm2 plist via python3
# ---------------------------------------------------------------------------
run_iterm2_patch() {
  local plist="$REPO_DIR/iterm2/com.googlecode.iterm2.plist"

  # Build palette JSON from PAL_* vars
  local json="{"
  local first=true
  for slot in $SLOTS; do
    if $first; then first=false; else json+=","; fi
    json+="\"$slot\":\"$(pal "$slot")\""
  done
  json+="}"

  PALETTE_JSON="$json" python3 - "$plist" <<'PYEOF'
import sys, plistlib, os, json

plist_path = sys.argv[1]
palette = json.loads(os.environ["PALETTE_JSON"])

# ANSI slot -> base24 slot mapping
ansi_slots = [
    "base01", "base08", "base0B", "base0A", "base0D", "base0E", "base0C", "base04",
    "base02", "base12", "base14", "base13", "base16", "base17", "base15", "base06",
]

def hex_to_components(hex_str):
    r = int(hex_str[0:2], 16) / 255.0
    g = int(hex_str[2:4], 16) / 255.0
    b = int(hex_str[4:6], 16) / 255.0
    return {"Red Component": r, "Green Component": g, "Blue Component": b,
            "Color Space": "sRGB"}

with open(plist_path, "rb") as f:
    plist = plistlib.load(f)

def patch_colors(d):
    for i, slot in enumerate(ansi_slots):
        key = f"Ansi {i} Color"
        if key in d:
            d[key] = hex_to_components(palette[slot])
    specials = {
        "Background Color": "base00",
        "Foreground Color": "base05",
        "Bold Color": "base07",
        "Cursor Color": "base05",
        "Cursor Text Color": "base00",
        "Selection Color": "base02",
        "Selected Text Color": "base07",
    }
    for key, slot in specials.items():
        if key in d:
            d[key] = hex_to_components(palette[slot])

for profile in plist.get("New Bookmarks", []):
    patch_colors(profile)

for preset_name, preset in plist.get("Custom Color Presets", {}).items():
    patch_colors(preset)

with open(plist_path, "wb") as f:
    plistlib.dump(plist, f)
PYEOF
  log_ok "Patched iTerm2 plist"
}

# ---------------------------------------------------------------------------
# Generate bin/colors swatch script
# ---------------------------------------------------------------------------
generate_bin_colors() {
  local out="$REPO_DIR/bin/colors"

  # Build RGB escape for a slot
  rgb_esc() {
    local hex r g b
    hex="$(pal "$1")"
    r=$(hex_r "$hex"); g=$(hex_g "$hex"); b=$(hex_b "$hex")
    printf '\\e[48;2;%d;%d;%dm' "$r" "$g" "$b"
  }

  local scheme_upper
  scheme_upper=$(echo "$SCHEME_NAME" | tr '[:lower:]' '[:upper:]')

  cat > "$out" <<SWATCH
#!/usr/bin/env bash
# Print ${SCHEME_NAME} color palette swatches
# Generated by theme/generate.sh - DO NOT EDIT

echo ""
echo "==============================================="
echo "      ${scheme_upper} COLOR PALETTE      "
echo "==============================================="
echo ""
echo "Background / Foreground"
echo "-----------------------"
printf "BG         $(rgb_esc base00)      \e[0m #$(pal base00)\n"
printf "BG_ALT     $(rgb_esc base01)      \e[0m #$(pal base01)\n"
printf "BG_HL      $(rgb_esc base02)      \e[0m #$(pal base02)\n"
printf "DIM        $(rgb_esc base03)      \e[0m #$(pal base03) (comments)\n"
printf "FG         $(rgb_esc base05)      \e[0m #$(pal base05)\n"
printf "FG_BRIGHT  $(rgb_esc base07)      \e[0m #$(pal base07)\n"
echo ""
echo "Accent Colors"
echo "-------------"
printf "RED        $(rgb_esc base08)      \e[0m #$(pal base08) (errors)\n"
printf "GREEN      $(rgb_esc base0B)      \e[0m #$(pal base0B) (success)\n"
printf "YELLOW     $(rgb_esc base0A)      \e[0m #$(pal base0A) (types)\n"
printf "BLUE       $(rgb_esc base0D)      \e[0m #$(pal base0D) (functions)\n"
printf "MAGENTA    $(rgb_esc base0E)      \e[0m #$(pal base0E) (keywords)\n"
printf "CYAN       $(rgb_esc base0C)      \e[0m #$(pal base0C) (strings)\n"
echo ""
echo "Bright Variants"
echo "---------------"
printf "BR_RED     $(rgb_esc base12)      \e[0m #$(pal base12)\n"
printf "BR_GREEN   $(rgb_esc base14)      \e[0m #$(pal base14)\n"
printf "BR_YELLOW  $(rgb_esc base09)      \e[0m #$(pal base09)\n"
printf "BR_BLUE    $(rgb_esc base16)      \e[0m #$(pal base16)\n"
printf "BR_MAGENTA $(rgb_esc base17)      \e[0m #$(pal base17)\n"
printf "BR_CYAN    $(rgb_esc base15)      \e[0m #$(pal base15)\n"
echo ""
echo "ANSI 16-color strip:"
printf "$(rgb_esc base01)  $(rgb_esc base08)  $(rgb_esc base0B)  $(rgb_esc base0A)  $(rgb_esc base0D)  $(rgb_esc base0E)  $(rgb_esc base0C)  $(rgb_esc base04)  \e[0m Normal 0-7\n"
printf "$(rgb_esc base02)  $(rgb_esc base12)  $(rgb_esc base14)  $(rgb_esc base13)  $(rgb_esc base16)  $(rgb_esc base17)  $(rgb_esc base15)  $(rgb_esc base06)  \e[0m Bright 8-15\n"
echo ""
SWATCH

  chmod +x "$out"
  log_ok "Generated bin/colors"
}

# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------
generate_colors_zsh
generate_vimrc
run_iterm2_patch
generate_bin_colors

log_ok "All targets generated for: ${SCHEME_NAME}"
