#!/bin/bash
############################
# packages/lib-mise-pins.sh
# Publish a bumped mise manifest as a PR.
#
# Sourced by sync.sh, which defines the log_* helpers.
# Every failure logs and returns 0, so a publish problem never aborts sync.
############################

readonly MISE_PINS_BRANCH="chore/mise-pins"

# Push the bumped manifest to the fixed branch off origin/main and open a PR.
# Plumbing builds the commit in a private index, so the checked-out branch,
# its index, and unrelated working-tree edits stay untouched.
# The pre-bump blob guards against publishing local content that origin/main
# does not hold: unpushed or stale edits would reach a public branch.
#   publish_mise_pin_bump <manifest> <pre_bump_blob>
publish_mise_pin_bump() {
    local manifest="$1" pre_blob="${2:-}" top rel branch="$MISE_PINS_BRANCH"
    local tmpdir index blob tree commit url remote repo upstream_blob
    top="$(git -C "$(dirname "$manifest")" rev-parse --show-toplevel 2>/dev/null)" || top=""
    rel="$(git -C "$(dirname "$manifest")" ls-files --full-name -- "$(basename "$manifest")" 2>/dev/null)" || rel=""
    if [[ -z "$top" || -z "$rel" ]]; then
        log_warning "mise manifest is not a tracked file in a git repo — no PR for the pin bump"
        return 0
    fi
    if ! git -C "$top" fetch --quiet origin main; then
        log_error "fetch of origin/main failed — pin bump not published; re-run dots sync"
        return 0
    fi

    upstream_blob="$(git -C "$top" rev-parse --verify --quiet "origin/main:$rel" 2>/dev/null)" || upstream_blob=""
    if [[ -z "$pre_blob" || "$pre_blob" != "$upstream_blob" ]]; then
        log_warning "local $rel differs from origin/main before the bump — pin bump kept locally, not published"
        return 0
    fi

    tmpdir="$(mktemp -d)" || {
        log_error "cannot create a temp dir — pin bump not published; re-run dots sync"
        return 0
    }
    index="$tmpdir/index"
    if ! { blob="$(git -C "$top" hash-object -w -- "$manifest")" \
        && GIT_INDEX_FILE="$index" git -C "$top" read-tree origin/main \
        && GIT_INDEX_FILE="$index" git -C "$top" update-index --add --cacheinfo "100644,$blob,$rel" \
        && tree="$(GIT_INDEX_FILE="$index" git -C "$top" write-tree)" \
        && commit="$(git -C "$top" commit-tree "$tree" -p origin/main -m 'chore(mise): bump pins' -m "Generated by dots sync after mise upgrade --bump. Only $rel changes.")" \
        && git -C "$top" push --quiet --force origin "+$commit:refs/heads/$branch"; }; then
        rm -rf "$tmpdir"
        log_error "pin bump commit or push failed — re-run dots sync"
        return 0
    fi
    rm -rf "$tmpdir"

    if ! command -v gh &>/dev/null; then
        log_warning "gh not found — $branch is pushed; open a PR by hand"
        return 0
    fi
    # Read the raw configured URL: `config --get` does not expand insteadOf.
    remote="$(git -C "$top" config --get remote.origin.url 2>/dev/null)" || remote=""
    if [[ "$remote" =~ github\.com[:/]([^/]+)/([^/]+)$ ]]; then
        repo="${BASH_REMATCH[1]}/${BASH_REMATCH[2]%.git}"
    else
        log_warning "origin is not a GitHub remote — $branch is pushed; open a PR by hand"
        return 0
    fi

    if ! url="$(gh pr list --repo "$repo" --head "$branch" --state open --json url --jq '.[0].url')"; then
        log_warning "gh pr list failed — $branch is pushed; open a PR by hand"
        return 0
    fi
    if [[ -n "$url" ]]; then
        log_success "mise pin bump PR updated: $url"
    elif url="$(gh pr create --repo "$repo" --base main --head "$branch" --title 'chore(mise): bump pins' --body "Generated by dots sync after mise upgrade --bump. Only $rel changes.")"; then
        log_success "mise pin bump PR: $url"
    else
        log_warning "gh pr create failed — $branch is pushed; open the PR by hand"
        return 0
    fi
    log_info "$rel stays modified until the PR merges; dots up carries it through the pull"
}
