#!/bin/bash
############################
# packages/lib-mise-pins.sh
# Publish a bumped mise manifest as an auto-merge PR, then settle the
# checkout once that PR merges.
#
# sync.sh and bin/dots source this file. Each defines the log_* helpers.
# Every failure logs and returns 0, so a pin problem never aborts sync.
############################

readonly MISE_PINS_BRANCH="chore/mise-pins"

# Print the commit at the tip of the remote pin branch; fail when it is absent.
#   mise_pin_branch_tip <top>
mise_pin_branch_tip() {
    git -C "$1" fetch --quiet origin "refs/heads/$MISE_PINS_BRANCH" 2>/dev/null || return 1
    git -C "$1" rev-parse --verify --quiet FETCH_HEAD
}

# Print the blob id of <rel> at <rev>; print nothing when it does not exist.
#   mise_pin_blob_at <top> <rev> <rel>
mise_pin_blob_at() {
    git -C "$1" rev-parse --verify --quiet "$2:$3" 2>/dev/null || true
}

# Succeed when the blob id <blob> is the <rel> content at a commit in
# HEAD..origin/main that touches <rel>.
#   mise_pin_blob_in_range <top> <blob> <rel>
mise_pin_blob_in_range() {
    local sha
    while IFS= read -r sha; do
        [[ "$(mise_pin_blob_at "$1" "$sha" "$3")" == "$2" ]] && return 0
    done < <(git -C "$1" rev-list HEAD..origin/main -- "$3" 2>/dev/null)
    return 1
}

# Push the bumped manifest to the fixed branch off origin/main, open a PR,
# and enable squash auto-merge on it.
# Plumbing builds the commit in a private index, so the checked-out branch,
# its index, and unrelated working-tree edits stay untouched.
# The pre-bump blob guards against publishing local content that is not
# public yet. It must match origin/main, or the open pin branch: a second
# sync before the PR merges starts from the bump that sync already pushed.
# The commit replaces the whole manifest, so the pin branch only counts while
# its parent still holds the origin/main manifest. Otherwise the PR would
# revert manifest edits that reached origin/main after it opened.
#   publish_mise_pin_bump <manifest> <pre_bump_blob>
publish_mise_pin_bump() {
    local manifest="$1" pre_blob="${2:-}" top rel branch="$MISE_PINS_BRANCH"
    local tmpdir index blob tree commit url="" remote repo upstream_blob tip prs pr_url pr_cross pr_oid
    top="$(git -C "$(dirname "$manifest")" rev-parse --show-toplevel 2>/dev/null)" || top=""
    rel="$(git -C "$(dirname "$manifest")" ls-files --full-name -- "$(basename "$manifest")" 2>/dev/null)" || rel=""
    if [[ -z "$top" || -z "$rel" ]]; then
        log_warning "mise manifest is not a tracked file in a git repo — no PR for the pin bump"
        return 0
    fi
    if ! git -C "$top" fetch --quiet origin main; then
        log_error "fetch of origin/main failed — pin bump not published; re-run dots sync"
        return 0
    fi

    upstream_blob="$(mise_pin_blob_at "$top" origin/main "$rel")"
    if [[ -n "$pre_blob" && "$pre_blob" != "$upstream_blob" ]] \
        && tip="$(mise_pin_branch_tip "$top")" \
        && [[ "$pre_blob" == "$(mise_pin_blob_at "$top" "$tip" "$rel")" ]] \
        && [[ "$(mise_pin_blob_at "$top" "$tip^" "$rel")" == "$upstream_blob" ]]; then
        upstream_blob="$pre_blob"
    fi
    if [[ -z "$pre_blob" || "$pre_blob" != "$upstream_blob" ]]; then
        log_warning "local $rel differs from origin/main and a current $branch before the bump — pin bump kept locally, not published"
        return 0
    fi

    tmpdir="$(mktemp -d)" || {
        log_error "cannot create a temp dir — pin bump not published; re-run dots sync"
        return 0
    }
    index="$tmpdir/index"
    if ! { blob="$(git -C "$top" hash-object -w -- "$manifest")" \
        && GIT_INDEX_FILE="$index" git -C "$top" read-tree origin/main \
        && GIT_INDEX_FILE="$index" git -C "$top" update-index --add --cacheinfo "100644,$blob,$rel" \
        && tree="$(GIT_INDEX_FILE="$index" git -C "$top" write-tree)" \
        && commit="$(git -C "$top" commit-tree "$tree" -p origin/main -m 'chore(mise): bump pins' -m "Generated by dots sync after mise upgrade --bump. Only $rel changes.")" \
        && git -C "$top" push --quiet --force origin "+$commit:refs/heads/$branch"; }; then
        rm -rf "$tmpdir"
        log_error "pin bump commit or push failed — re-run dots sync"
        return 0
    fi
    rm -rf "$tmpdir"

    if ! command -v gh &>/dev/null; then
        log_warning "gh not found — $branch is pushed; open a PR by hand"
        return 0
    fi
    # Read the raw configured URL: `config --get` does not expand insteadOf.
    remote="$(git -C "$top" config --get remote.origin.url 2>/dev/null)" || remote=""
    if [[ "$remote" =~ github\.com[:/]([^/]+)/([^/]+)$ ]]; then
        repo="${BASH_REMATCH[1]}/${BASH_REMATCH[2]%.git}"
    else
        log_warning "origin is not a GitHub remote — $branch is pushed; open a PR by hand"
        return 0
    fi

    # `gh pr list --head` ignores the owner, so a fork PR from a same-named
    # branch can appear. Ignore fork PRs; accept a same-repo PR at our commit.
    if ! prs="$(gh pr list --repo "$repo" --head "$branch" --state open --json number,url,isCrossRepository,headRefOid --jq '.[] | [.url, .isCrossRepository, .headRefOid] | @tsv')"; then
        log_warning "gh pr list failed — $branch is pushed; open a PR by hand"
        return 0
    fi
    local own_prs=0
    while IFS=$'\t' read -r pr_url pr_cross pr_oid; do
        [[ "$pr_cross" == "false" ]] || continue
        own_prs=$((own_prs + 1))
        if [[ "$pr_oid" == "$commit" ]]; then
            url="$pr_url"
            break
        fi
    done <<< "$prs"
    if [[ -n "$url" ]]; then
        log_success "mise pin bump PR updated: $url"
    elif ((own_prs > 0)); then
        log_warning "open $branch PR from this repo is not at $commit — no auto-merge; check the PR by hand"
        return 0
    elif url="$(gh pr create --repo "$repo" --base main --head "$branch" --title 'chore(mise): bump pins' --body "Generated by dots sync after mise upgrade --bump. Only $rel changes.")"; then
        log_success "mise pin bump PR: $url"
    else
        log_warning "gh pr create failed — $branch is pushed; open the PR by hand"
        return 0
    fi
    if gh pr merge "$url" --auto --squash --match-head-commit "$commit" >/dev/null; then
        log_success "auto-merge enabled: the PR merges when its checks pass"
    else
        log_warning "gh pr merge --auto failed — merge $url by hand"
    fi
    log_info "$rel stays modified until the PR merges; the next dots sync after the merge cleans it"
}

# Fast-forward main to origin/main when the only thing that holds it back is
# the pin bump. `dots sync` calls this before .sync, so a run never rewrites
# the scripts it executes. It acts only when the checkout is on main, main is
# behind origin/main, and the user has not staged the manifest. Three cases:
#
# - The pin PR merged: the dirty manifest equals the origin/main manifest.
#   Staging it makes the index match the incoming tree, so git does not count
#   it as a local change that blocks the fast-forward.
# - origin/main changed the manifest while the pin PR was open: the dirty
#   manifest equals the pin branch tip, whose parent manifest is stale. That
#   bump is public, so the checkout drops it and fast-forwards. The same sync
#   then bumps again and pushes a fresh commit on top of origin/main.
# - The pin PR merged and origin/main edited the manifest afterwards: the
#   pin branch is gone, but the dirty manifest equals the manifest at one of
#   the incoming commits. That bump is public, so the checkout drops it.
#
# Git refuses when other local edits overlap the incoming commits; the
# manifest then goes back to its dirty content, unstaged.
#   settle_mise_pin_bump <manifest>
settle_mise_pin_bump() {
    local manifest="$1" top rel blob upstream_blob tip mode
    top="$(git -C "$(dirname "$manifest")" rev-parse --show-toplevel 2>/dev/null)" || top=""
    rel="$(git -C "$(dirname "$manifest")" ls-files --full-name -- "$(basename "$manifest")" 2>/dev/null)" || rel=""
    [[ -n "$top" && -n "$rel" ]] || return 0
    git -C "$top" diff --quiet HEAD -- "$rel" && return 0
    [[ "$(git -C "$top" symbolic-ref --quiet --short HEAD 2>/dev/null)" == "main" ]] || return 0
    git -C "$top" diff --cached --quiet -- "$rel" || return 0
    if ! git -C "$top" fetch --quiet origin main; then
        log_warning "fetch of origin/main failed — cannot check whether the mise pin PR merged"
        return 0
    fi

    blob="$(git -C "$top" hash-object -w -- "$manifest")" || return 0
    upstream_blob="$(mise_pin_blob_at "$top" origin/main "$rel")"
    if [[ "$blob" == "$upstream_blob" ]]; then
        mode=merged
    elif tip="$(mise_pin_branch_tip "$top")" \
        && [[ "$blob" == "$(mise_pin_blob_at "$top" "$tip" "$rel")" ]]; then
        # A current pin PR is the normal open state: stay quiet.
        [[ "$(mise_pin_blob_at "$top" "$tip^" "$rel")" != "$upstream_blob" ]] || return 0
        mode=stale
    elif mise_pin_blob_in_range "$top" "$blob" "$rel"; then
        mode=history
    else
        # An edit on an up-to-date main is the user's own work: stay quiet.
        [[ "$(git -C "$top" rev-parse HEAD)" != "$(git -C "$top" rev-parse origin/main)" ]] || return 0
        log_warning "$rel differs from HEAD and matches no public mise pin bump — it stays modified"
        return 0
    fi
    if ! git -C "$top" merge-base --is-ancestor HEAD origin/main; then
        log_warning "local main has commits origin/main lacks — $rel stays modified"
        return 0
    fi

    if [[ "$mode" == merged ]]; then
        git -C "$top" add -- "$rel" || return 0
    else
        git -C "$top" checkout --quiet HEAD -- "$rel" || return 0
    fi
    if ! git -C "$top" merge --ff-only --quiet origin/main; then
        [[ "$mode" == merged ]] || git -C "$top" cat-file blob "$blob" > "$manifest" || true
        git -C "$top" reset --quiet -- "$rel" 2>/dev/null || true
        log_warning "local edits block the fast-forward to origin/main — $rel stays modified"
        return 0
    fi
    case "$mode" in
        merged) log_success "mise pin PR merged — main fast-forwarded to origin/main" ;;
        stale) log_info "origin/main moved past the open mise pin PR — main fast-forwarded; this sync bumps the pins again" ;;
        history) log_info "mise pin PR merged and origin/main edited the manifest since — main fast-forwarded; this sync bumps the pins again" ;;
    esac
}
